# Generated by Django 5.0.6 on 2024-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sum_rate',
            field=models.IntegerField(default=0),
        ),
    ]
