# Generated by Django 5.0.6 on 2024-06-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_sum_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stars',
            new_name='StarsOfUsers',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_raters',
        ),
        migrations.RemoveField(
            model_name='book',
            name='star',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sum_rate',
        ),
        migrations.CreateModel(
            name='StarsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=0)),
                ('sum_rate', models.IntegerField(default=0)),
                ('number_of_raters', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars_book', to='books.book')),
            ],
        ),
    ]
