# Generated by Django 5.0.6 on 2024-06-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
