# Generated by Django 5.0.6 on 2024-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_bookreservation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
