# Generated by Django 5.0.6 on 2024-06-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_bookreservation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrent',
            name='status',
            field=models.CharField(choices=[('Kitob berilgan', 'Kitob berilgan'), ('Kitob qaytarilgan', 'Kitob qaytarilgan')], default='Kitob berilgan', max_length=20),
        ),
    ]
