# Generated by Django 5.0.6 on 2024-06-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_bookrent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrent',
            name='finaly_price',
            field=models.FloatField(default=0),
        ),
    ]
