# Generated by Django 5.0.6 on 2024-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_bookrent_finaly_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrent',
            old_name='finaly_price',
            new_name='finally_price',
        ),
        migrations.AddField(
            model_name='bookrent',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
