# Generated by Django 5.0.6 on 2024-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rename_finaly_price_bookrent_finally_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrent',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
